name: logic_study_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get: ^4.6.5
  flutter_svg: ^2.0.7
  http:
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  fluttertoast: ^8.2.2
  overlay_support: ^2.1.0
  video_player: ^2.7.0
  cached_network_image: ^3.2.3
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  
  fonts:
    - family: omnes bold
      fonts:
        - asset: fonts/OMNES-ARABIC-BOLD.ttf
    - family: omnes
      fonts:
        - asset: fonts/OMNES-ARABIC-REGULAR.ttf

